FROM ghcr.io/tauffer-consulting/domino-base-piece:gpu

# Install specific requirements
RUN apt update
RUN apt install ffmpeg -y

# Need to copy operators source code
COPY config.toml flowui/operators_repository/
COPY operators flowui/operators_repository/operators
COPY .flowui flowui/operators_repository/.flowui

# Install specific python dependencies
RUN pip install transformers==4.34.1

# Dowload transformers model
RUN python -c "import huggingface_hub; huggingface_hub.snapshot_download('facebook/bart-large-cnn')"