# Use the base image
FROM ghcr.io/tauffer-consulting/domino-base-piece:latest

RUN apt-get update && \
    apt-get install -y \
    python3-dev \
    python3-pip \
    libopencv-dev

RUN pip3 install opencv-python-headless

