FROM ghcr.io/tauffer-consulting/domino-airflow-pod:gpu

# Install specific requirements
RUN apt update
RUN apt install ffmpeg -y
RUN apt install git -y

# Need to copy operators source code
COPY config.toml flowui/operators_repository/
COPY operators flowui/operators_repository/operators
COPY .flowui flowui/operators_repository/.flowui

# Install specific python dependencies
RUN pip install -U openai-whisper

# Dowload Whisper model
RUN python -c "import whisper; whisper.load_model('base')"